export default `food,ruoka,legal,description,Lisätieto
Acorn Squash,Acorn Squash,Legal,,
Agar-agar,Agar-agar,Illegal,,
Agave syrup,agavesiirappi,Illegal,,
Algae,levä,Illegal,,
Allspice,Maustepippuri,Legal,,
Almond butter,Mantelivoi,Legal,,
Almond milk,mantelimaito,Legal,,
Almond oil,manteliöljy,Legal,,
Almonds,manteli,Legal,,
Aloe Vera,Aloe Vera,Illegal,,
Amaranth flour,Amaranth jauho,Illegal,,
Anchovies,anjovis,Legal,,
Apple Juice,omenamehu (sokeroimaton),Legal,,
Apples,omena,Legal,,
Apricots,aprikoosi,Legal,,
Arrowroot,Arrowjuuri,Illegal,,
Artichokes (French),Artisokka (ranska),Legal,,
Artichokes (Jerusalem),Artisokka (Jerusalem),Illegal,,
Ascorbic acid,Askorbiinihappo,Legal,,
Asiago cheese,Asiago juusto,Legal,,
Asparagus,Parsa,Legal,,
Aspartame,aspartaami,Legal,,
Aspartic acid,Asparagiinihappo,Legal,,
Astragalus,kurjenherne,Illegal,,
Avocado oil,avokadoöljy,Legal,,
Avocadoes,avokado,Legal,,
Bacon,Pekoni,Legal,,
Baker's yeast,leivinhiiva,Illegal,,
Baking powder,Leivinjauhe,Illegal,,
Baking soda,Ruokasooda,Legal,,
Balsamic vinegar,balsamiviinietikka,Illegal,,
Bananas,banaani,Legal,,
Bark tea,Pau d'Arco tee,Illegal,,
Barley,Ohra,Illegal,,
Basil,Basilika,Legal,,
Bay Leaf,Laakerinlehti,Legal,,
Bean flour,papujauhot,Illegal,,
Bean sprouts,Pavunidut,Illegal,,
Bee Pollen,Siitepöly,Illegal,,
Beef,naudanliha,Legal,,
Beer,Olut,Illegal,,
Beets,punajuuri,Legal,,
Berries,marjat,Legal,,
Bhindi,Okra,Illegal,,
Bitter Gourd,karvaskurkku,Illegal,,
Black beans,musta papu,Legal,,
Black eye beans,lehmänpapu / pitkäpapu,Illegal,,
Black radish,Retikka,Legal,,
Blue cheese,Sinihomejuusto,Legal,,
Bok Choy,pinaattikiinankaali,Legal,,
Bologna,Bologna,Illegal,,
Bouillon cubes,Liemikuutiot,Illegal,,
Bourbon,Bourbon,Legal,,
Brandy,Brandy,Illegal,,
Brazil nuts,brasilialainen pähkinä,Legal,,
Brick cheese,Brick juusto,Legal,,
Brie cheese,brie juusto,Legal,,
Broccoli,Parsakaali,Legal,,
Brussell sprouts,ruusukaali,Legal,,
Buckwheat,Tattari,Illegal,,
Bulgur,bulgur,Illegal,,
Burdock root,takiaisen juuri,Illegal,,
Butter,voi,Legal,,
Butter beans,voipapu,Illegal,,
Buttermilk,piimä,Illegal,,
Butternut squash,myskikurpitsa,Legal,,
Cabbage,Kaali,Legal,,
Camembert cheese,Camembert juusto,Legal,,
Canellini beans,Canellini pavut,Illegal,,
Canned fish,Kalasäilykkeet,Legal,,
Canned fruits,säilykehedelmät,Illegal,,
Canned vegetables,vihannessäilykkeet,Illegal,,
Canola oil,rypsiöljy,Legal,,
Cantaloupe,verkkomeloni,Legal,,
Capers,kapris,Legal,,
Carob,johanneksenleipäpuu,Illegal,,
Carrageenan,karrageeni,Illegal,,
Carrots,Porkkana,Legal,,
Cashews,cashew,Legal,,
Cauliflower,Kukkakaali,Legal,,
Celeriac /celery root,Mukulaselleri / sellerin juuri,Legal,,
Celery,Selleri,Legal,,
Cellulose (in supplements),Selluloosa (lisäravinteissa),Legal,,
Cellulose Gum,selluloosakumi,Illegal,,
Cereals,Murot,Illegal,,
Chard,Lehtimangoldi,Legal,,
Cheddar cheese,Cheddar-juusto,Legal,,
Cheese,Juusto,Legal,,
Cherimoya,kirimoija,Legal,,
Cherries,kirsikat,Legal,,
Chestnut flour,kastanjajauhot,Illegal,,
Chestnuts,kastanjat,Legal,,
Chevre,Chevre,Illegal,,
Chewing gum,Purukumi,Illegal,,
Chick peas,kikherne,Illegal,,
Chickory root,sikurijuuri,Illegal,,
Chlorella,chlorella,Illegal,,
Chocolate,Suklaa,Illegal,,
Cilantro,Korianteri ,Legal,,
Cinnamon,Kaneli,Legal,,
Citric Acid,Sitruunahappo,Legal,,
Club soda,Soodavesi,Legal,,
Cocoa powder,Kaakaojauhe,Illegal,,
Coconut,kookospähkinä,Legal,,
Coconut milk,Kookosmaito,Legal,,
Coconut oil,Kookosöljy,Legal,,
Coffee,kahvi,Legal,,
Coffee (instant),pikakahvi,Illegal,,
Colby cheese,Colby juusto,Legal,,
Collard greens,Rehuydinkaali,Legal,,
Cordials,Liköörit / mehutiivisteet,Illegal,,
Corn,Maissi,Illegal,,
Corn oil,Maissiöljy,Legal,,
Corn syrup,maissisiirappi,Illegal,,
Cornstarch,Maissitärkkelys,Illegal,,
Cottage cheese,Raejuusto,Illegal,,
Courgette,Kesäkurpitsa,Legal,,
Cranberry juice,Karpalomehu,Legal,,
Cream,Kerma,Illegal,,
Cream cheese,Kermajuusto,Illegal,,
Cream of Tartar,Viinikivi,Illegal,,
Croscomellose sodium,Kroskarmelloosi,Illegal,,
Cucumbers,kurkku,Legal,,
Cyclamate,syklamaatti,Legal,,
Date sugar,taatelisokeri,Illegal,,
Dates,taateli,Legal,,
Decaffeinated Products,kofeiinittomat Tuotteet,Illegal,,
Dextrose (contained in commercial products),dekstroosi,Illegal,,
Dry Curd Cottage Cheese (DCCC),Kuiva Rahka tuorejuusto (DCCC),Legal,,
Durum Flour,Durumvehnäjauho,Illegal,,
Echinacea,Echinacea,Legal,,
Edam cheese,edamjuusto,Legal,,
Eggplant,Munakoiso,Legal,,
Eggs,kananmuna,Legal,,
Ethanol,etanoli,Legal,,
Evaporated cane juice,sokeriruo'on kuivattu mehu,Illegal,,
Ezekiel Bread,Ezekiel Leipä,Illegal,,
Faba beans,härkäpapu,Illegal,,
Fenugreek,Sarviapila,Illegal,,
Feta Cheese,Fetajuusto,Illegal,,
Figs,viikunat,Legal,,
Filberts (hazelnuts),hasselpähkinä,Legal,,
Fish,kala,Legal,,
Flax seed,pellavansiemenet,Illegal,,
Flax seed oil,Pellavansiemenöljy,Legal,,
Flour,Jauhot,Illegal,,
FOS,FOS,Illegal,,
Fowl,riistalintu,Legal,,
Orange Juice (concentrated),"appelsiinimehu (tiiviste, sokeroimaton)",Legal,,
Fructose (granulated),fruktoosi,Illegal,,
Fruits (canned),hedelmäsäilykkeet,Legal,,
Garbanzo beans,garbanzo pavut,Illegal,,
Garfava flour,Garfava jauhot,Illegal,,
Garlic,Valkosipuli,Legal,,
Gelatin (unflavored),Gelatiini (maustamaton),Legal,,
Ghee,ghee,Legal,,
Gin,Gin,Legal,,
Ginger,Inkivääri,Legal,,
Gjetost cheese,Gjetost juusto,Illegal,,
Glucose candy,glukoosi karkki,Illegal,,
Glycerin,glyseriini,Legal,,
Glycerol,glyseroli,Legal,,
Goatein,Goatein,Illegal,,
Gorgonzola cheese,gorgonzola juusto,Legal,,
Gouda cheese,gouda juusto,Legal,,
Granulated glucose,glukoosi,Illegal,,
Grape juice,Greippimehu,Legal,,
Grapefruit,Greippi,Legal,,
Grapefruit juice,greippimehu (sokeroimaton),Illegal,,
Grapes,viinirypäleet,Legal,,
Grapeseed oil,Rypälesiemenöljy,Legal,,
Green tea,Vihreä tee,Legal,,
Gruyere cheese,Gruyère juusto,Legal,,
Guar Gum,Guarkumi,Illegal,,
Gums,kumit,Illegal,,
Ham,kinkku (prosessoimaton),Legal,,
Haricot beans,Valkoinen papu,Legal,,
Havarti cheese,Havarti juusto,Legal,,
Hazelnuts (filberts),Hasselpähkinä,Legal,,
Hemp protein powder,Hamppuproteiinijauhe,illegal,,
Hemp seed,Hampun siemen,illegal,,
Homemade yogurt,kotitekoinen scd-jogurtti,Legal,,
Honey,Hunaja,Legal,,
Horseradish,piparjuuri,Legal,,
Hot dogs,hot dog,Illegal,,
Hydrolyzed Protein,hydrolysoitu proteiini,Illegal,,
Ice cream,jäätelö,Illegal,,
Inositol,inositoli,Illegal,,
Inulin,inuliini,Illegal,,
Iron supplements,rautalisät,Illegal,,
Isoglucose,isoglukoosia,Illegal,,
Jaggery (gur),raakasokeri,Illegal,,
Jalapenos,jalapeno,Legal,,
Jicama,jicama,Illegal,,
Juice from concentrate,mehutiiviste,Illegal,huom. Suomessa lisätty sokeri aina mainittu,
Kale,Lehtikaali,Legal,,
Kefir,Kefiiri ,Illegal,,
Ketchup,Ketsuppi,Illegal,,
Kidney beans,Kidney-pavut,Legal,,
Kimchi,Kimchi,Legal,,
Kiwi fruit,kiivi,Legal,,
Kohlrabi,Kyssäkaali,Illegal,,
Konjac,konjakki,Illegal,,
Kudzu (or kuzu),Kudzu (tai kuzu),Illegal,,
Kumquats,Kumkvatit,Legal,,
KyoGreen powder,KyoGreen jauhe,Illegal,,
L-Theanine,L-Teaniini,Legal,,
Lactaid Milk,Lactaid Maito,Illegal,,
Lactose Hydrolyzed Milk,Laktoosi Hydrolysoitu maito,Illegal,,
Lamb,lammas,Legal,,
Lecithin,lesitiini,Legal,,
Leek,Purjo,Legal,,
Lemons,Sitruuna ,Legal,,
Lentils,linssit,Legal,,
Lettuce,Lehtisalaatti,Legal,,
leucine,leusiini,Legal,,
Licorice,Lakritsi,Illegal,,
Lignin,ligniini,Illegal,,
Lima beans,Limanpapu / voipapu,Legal,,
Limburger cheese,Limburger juusto,Legal,,
Limes,limetti,Legal,,
Liqueurs,liköörit,Illegal,,
Liquid Clorychlorophyll,nestemäinen Clorychlorophyll,Illegal,,
Macadamia nuts,Macadamiapähkinät,Legal,,
Macadamia oil,macadamiaöljy,Legal,,
Magnesium citrate,magnesiumsitraatti,Legal,,
Magnesium Stearate,magnesiumstearaatti,Legal,,
Maltitol,maltitoli,Illegal,,
Maltodextrin,maltodekstriini,Illegal,,
Manchego Cheese,Manchegojuusto,Legal,,
Mangoes,mango,Legal,,
Mannitol,mannitoli,Illegal,,
Maple syrup,vaahterasiirappi,Illegal,,
Margarine,Margariini,Illegal,,
Marshmallow,vaahtokaramelli,Illegal,,
Mead,Sima,Illegal,,
Meats,Lihat,Legal,,
Meats (canned),Liha (säilyke),Illegal,,
Meats (processed),Liha (käsitelty),Illegal,,
Melatonin,Melatoniini,Illegal,,
Melon,Meloni,Legal,,
Milk,Maito,Illegal,,
Millet,Hirssi,Illegal,,
Miso,miso,Illegal,,
Molasses,Melassi,Illegal,,
Monterey Jack cheese,Monterey Jack juusto,Legal,,
Mozzarella cheese,Mozzarella juusto,Illegal,,
MSG,Natriumglutamaatti,Illegal,,
Mucilaginous Herbs,geeliytyvät Yrtit,Illegal,,
Mucilaginous Polysaccharides,Geeliytyvä Polysakkaridi,Illegal,,
Muenster cheese,Muenster juusto,Legal,,
Mungbeans,mungopapu,Illegal,,
Mushrooms,sienet,Legal,,
Mustard (plain),Sinappi (tavallinen),Legal,,
Natural Flavors,luontaiset aromit,Illegal,,
Navy beans,Valkoinen papu,Legal,,
Nectarines,nektariini,Legal,,
Nettles,nokkonen,Illegal,,
Neufchatel cheese,neufchâtel juusto,Illegal,,
Noni Juice,Nonimehu,Illegal,,
Nutmeg,Muskottipähkinä,Legal,,
Oats,Kaura,Illegal,,
Okra,okra,Illegal,,
Olive oil,Oliiviöljy,Legal,,
Olives,oliivi,Legal,,
Onions,sipuli,Legal,,
Orange juice,appelsiinimehu,Legal,,
Oranges,appelsiini,Legal,,
Oregano,Oregano,Legal,,
Papayas,papaija,Legal,,
Pappadum,Papadum,Illegal,,
Paprika,Paprika,Legal,,
Parmesan cheese,parmesan juusto,Legal,,
Parsley,Persilja,Legal,,
Parsnips,palsternakka,Illegal,,
Passion Fruit,Passion hedelmä,Legal,,
Pasta,Pasta,Illegal,,
Pau 'Arco,Pau 'Arco,Illegal,,
Pea flour,hernejauho,Illegal,,
Peaches,persikat,Legal,,
Peanut butter,Maapähkinävoi,Legal,,
Peanut Oil,Maapähkinäöljy,Legal,,
Peanuts,maapähkinät,Legal,,
Pears,päärynä,Legal,,
Peas,herneet,Legal,,
Pecans,pekaanipähkinä,Legal,,
Pectin,pektiini,Illegal,,
Peppermint tea,piparminttutee,Legal,,
Peppers,pippurit,Legal,,
Peptizyde,Peptizyde,Legal,,
Persimmons,persimoni,Legal,,
Phosphatidylcholine,fosfatidyylikoliini,Legal,,
Pickles (dill),Suolakurkku (tilli),Illegal,,
Pine nuts,pinjansiemen,Legal,,
Pineapple,Ananas,Legal,,
Pineapple juice,ananasmehu (sokeroimaton),Legal,,
Pinto beans,Pinto pavut,Illegal,,
Pistachio nuts,pistaasipähkinä,Legal,,
Plantains,Keittobanaani,Illegal,,
Plums,luumu,Legal,,
Polysorbate 80,polysorbaatti 80,Illegal,,
Pomegranate concentrate,granaattiomena tiiviste,Illegal,,
Pork,sianliha,Legal,,
Pork Rinds,Kamara,Legal,,
Port du Salut cheese,Port du Salut juusto,Legal,,
Port wine,portviini,Illegal,,
Postum,Postum kahvinkorvike,Illegal,,
Potassium Sorbate,kaliumsorbaattia,Legal,,
Potatoes,peruna,Illegal,,
Poultry,Siipikarja,Legal,,
Primal Defense,Primal Defence,Illegal,,
Primost cheese,Primost juusto,Illegal,,
Processed cheeses,sulatejuusto,Illegal,,
Protein powder,Proteiinijauhe,Illegal,,
Provolone cheese,Provolone-juusto,Legal,,
Prunes,kuivatut luumut,Legal,,
Psyllium husks,psylliumin kuoret,Illegal,,
Pumpkin,Kurpitsa,Legal,,
Pumpkin (canned),Kurpitsa (säilyke),Illegal,,
Quinoa,Kvinoa,Illegal,,
Quorn,Quorn,Illegal,,
Raisins,rusina,Legal,,
Rhubarb,Raparperi,Legal,,
Rice,Riisi,Illegal,,
Rice Bran,Riisilese,Illegal,,
Rice Flour,Riisijauho,Illegal,,
Ricotta cheese,Ricotta juusto,Illegal,,
Romano cheese,Romano juusto,Legal,,
Roquefort cheese,Roquefort,Legal,,
Rosemary,Rosmariini,Legal,,
Rutabaga,Lanttu,Legal,,
Rye,ruis,Illegal,,
Tabasco sauce,Tabasco,Illegal,,
Tagatose,tagatoosi,Illegal,,
Tamari,tamari-soijakastike,Illegal,,
Tamarind,Tamarindi hedelmä,Illegal,,
Tangerines,mandariinit,Legal,,
Tapioca,Tapioka,Illegal,,
Tapioca Flour,tapiokajauho,Illegal,,
Taro,Taro,Illegal,,
Tarragon,Rakuuna,Legal,,
Tea,tee,Legal,,
Thyme,Timjami,Legal,,
Tofu,tofu,Illegal,,
Tofutti cheese,Tofutti juusto,Illegal,,
tomato,tomaatti,Legal,,
Tomato juice (canned),Tomaattimehu (säilyke),Legal,,
Tomato paste (canned),tomaatti pyree,Illegal,,
Tomato purée (canned),"Tomaattisose (säilyke, sokeroimaton)",Legal,,
Tomato sauce (canned),Tomaattikastike (säilyke),Illegal,,
Triticale,ruisvehnä,Illegal,,
Turbinado,täysruokosokeri,Illegal,,
Turnips,nauris,Illegal,,
V8 Juice,V8 mehu,Illegal,,
Vanillin,vanilja,Legal,,
Vegetable stearate,rasvahappojen suolat / magnesiumstearaatti,Legal,,
Vegetables (canned),Kasvikset (purkitettu),Illegal,,
Vinegar,Etikka,Legal,,
Vodka,Vodka,Legal,,
Saccharin,sakariini,Legal,,
Safflower oil,Safloriöljy,Legal,,
Sage,Salvia,Legal,,
Sago starch,saago,Illegal,,
Sake,Sake,Illegal,,
Salt,Suola,Legal,,
Sashimi,sashimi,Legal,,
saukerkraut,hapankaali,Legal,,
Seaweed,merilevä,Illegal,,
Seed Butters,siemenvoit,Illegal,,
Seed Flour,siemenjauhot,Illegal,,
Seeds,Siemenet,Legal,,
Sesame oil,seesamiöljy,Legal,,
Sesame seeds,seesaminsiemen,Illegal,,
Sharifa,annoona,Legal,,
Shellfish,äyriäiset,Legal,,
Sherry,Sherry,Illegal,,
Silica / Silicon Dioxide,Piidioksidi,Legal,,
Slippery elm,liukas jalava,Illegal,,
Smoked meats,Savustettu liha,Illegal,,
Sodium Benzoate,Natriumbentsoaatti,Legal,,
Sodium starch glycinate,Natriumtärkkelysglykolaatti glysinaatti,Illegal,,
Sorbitol,sorbitoli,Illegal,,
Sour cream,hapankerma,Illegal,,
Soy,Soija,Illegal,,
Soy Lecithin,Soijalesitiini,Legal,,
Soy Sauce,Soijakastike,Illegal,,
Soybean milk,soijamaito,Illegal,,
Soybean oil,soijapapuöljy,Illegal,,
Soybeans,soijapapu,Illegal,,
Spearmint Tea,viherminttu tee,Legal,,
Spelt,speltti,Illegal,,
Spices,Mausteet,Legal,,
Spinach,Pinaatti,Legal,,
Spirulina,spirulina,Illegal,,
Splenda,Splenda,Illegal,,
Split peas,herne,Legal,,
Sprouted Grain Bread,Idätetty jyvä leipä,Illegal,,
Squash,kurpitsa,Legal,,
Stevia,Stevia,Illegal,,
Stilton cheese,stilton juusto,Legal,,
String beans,vihreä papu,Legal,,
Sucralose,sukraloosi,Illegal,,
Sulphites,sulfiitti,Legal,,
Sunflower oil,Auringonkukka öljy,Legal,,
Swede,Lanttu,Legal,,
Sweet Potatoes,bataatti,Illegal,,
Swiss cheese,Sveitsinjuustot,Legal,,
Xantham Gum,ksantaanikumi,Illegal,,
xylitol,ksylitoli,Illegal,,
Zucchini,Kesäkurpitsa,Legal,,
Yams,jamssi,Illegal,,
Yoghurt (commercial),Jogurtti(kaupan),Illegal,,
Yoghurt (homemade),Jogurtti (kotitekoinen),Legal,,
Yucca Root,Jukka juuri,Illegal,,
sugar,sokeri,Illegal,,
cane sugar,ruokosokeri,Illegal,,
syrup,siirappi,Illegal,,
,siideri,Illegal,,
oat milk,kauramaito,Illegal,,
almond milk (homemade),mantelimaito (itse tehty),Legal,,
,lonkero,Illegal,,
rum,rommi,Illegal,,
lactose-free milk,laktoositon maito,Illegal,,
lactose-free dairy,laktoosittomat maitotuotteet,Illegal,,
pork,porsaanliha,Legal,,
candy,karkki,Illegal,,
sweets,makeiset,Illegal,,
coco,kaakao,Illegal,,
cocoa,kaakaojauhe,Illegal,,
cocoa butter,kaakaovoi,Legal,,
coconut flour,kookosjauho,Legal,,
tuna (canned),tonnikala (säilyke),Legal,,
spice blends,maustesekoitukset,Illegal,,`
